import time
         
                 #   cameraoption=device(text="Camera").exists
                 #   if cameraoption:
                 #       device(text="Camera").click()
                 #       allowonlywhileusingtheapp=device(className="android.view.ViewGroup",resourceId="android:id/decor_content_parent",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="1").child(className="android.view.ViewGroup",index="0").child(className="android.widget.FrameLayout",resourceId="com.android.permissioncontroller:id/nav_host_fragment",index="0").child(className="android.widget.LinearLayout",resourceId="com.android.permissioncontroller:id/app_permission_root",index="0").child(className="android.widget.ScrollView",resourceId="com.android.permissioncontroller:id/nested_scroll_view",index="0").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.LinearLayout",index="2").child(className="android.widget.RadioGroup",resourceId="com.android.permissioncontroller:id/radiogroup",index="1").child(className="android.widget.RadioButton",resourceId="com.android.permissioncontroller:id/allow_foreground_only_radio_button",index="0").exists
                 #       if allowonlywhileusingtheapp:
                 #           device(className="android.view.ViewGroup",resourceId="android:id/decor_content_parent",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="1").child(className="android.view.ViewGroup",index="0").child(className="android.widget.FrameLayout",resourceId="com.android.permissioncontroller:id/nav_host_fragment",index="0").child(className="android.widget.LinearLayout",resourceId="com.android.permissioncontroller:id/app_permission_root",index="0").child(className="android.widget.ScrollView",resourceId="com.android.permissioncontroller:id/nested_scroll_view",index="0").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.LinearLayout",index="2").child(className="android.widget.RadioGroup",resourceId="com.android.permissioncontroller:id/radiogroup",index="1").child(className="android.widget.RadioButton",resourceId="com.android.permissioncontroller:id/allow_foreground_only_radio_button",index="0").click()
       
def allowonlywhileusingtheapp(device,permissions):
    __openYoutube(device)
    device.press('recent')
    print(permissions)
    __longpressontherecentapp(device,permissions)
        
def __longpressontherecentapp(device,permissions):
    print(permissions)
    longpressonrecentapp=device(className="android.widget.FrameLayout",resourceId="net.oneplus.launcher:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.FrameLayout",resourceId="net.oneplus.launcher:id/launcher",index="0").child(className="android.widget.FrameLayout",resourceId="net.oneplus.launcher:id/drag_layer",index="0").child(className="android.widget.ListView",resourceId="net.oneplus.launcher:id/overview_panel",index="2").child(className="android.widget.FrameLayout",index="0").child(className="android.view.View",resourceId="net.oneplus.launcher:id/snapshot",index="1").exists
    print(longpressonrecentapp)
    if longpressonrecentapp:
        print("Longpress working")
        device(className="android.widget.FrameLayout",resourceId="net.oneplus.launcher:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.FrameLayout",resourceId="net.oneplus.launcher:id/launcher",index="0").child(className="android.widget.FrameLayout",resourceId="net.oneplus.launcher:id/drag_layer",index="0").child(className="android.widget.ListView",resourceId="net.oneplus.launcher:id/overview_panel",index="2").child(className="android.widget.FrameLayout",index="0").child(className="android.view.View",resourceId="net.oneplus.launcher:id/snapshot",index="1").long_click()
        appinfo=device(className="android.widget.FrameLayout",resourceId="net.oneplus.launcher:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.FrameLayout",resourceId="net.oneplus.launcher:id/launcher",index="0").child(className="android.widget.FrameLayout",resourceId="net.oneplus.launcher:id/drag_layer",index="0").child(className="android.widget.LinearLayout",resourceId="net.oneplus.launcher:id/menu_option_layout",index="0").child(className="android.widget.LinearLayout",index="1").child(className="android.widget.TextView",resourceId="net.oneplus.launcher:id/text",index="1").exists
        if appinfo:
            print("Clicking on app info")
            device(className="android.widget.FrameLayout",resourceId="net.oneplus.launcher:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.FrameLayout",resourceId="net.oneplus.launcher:id/launcher",index="0").child(className="android.widget.FrameLayout",resourceId="net.oneplus.launcher:id/drag_layer",index="0").child(className="android.widget.LinearLayout",resourceId="net.oneplus.launcher:id/menu_option_layout",index="0").child(className="android.widget.LinearLayout",index="1").child(className="android.widget.TextView",resourceId="net.oneplus.launcher:id/text",index="1").click()
            time.sleep(2)
            permissionstab=device(className="android.widget.FrameLayout",resourceId="com.android.settings:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.FrameLayout",resourceId="com.android.settings:id/content_parent",index="0").child(className="android.widget.FrameLayout",resourceId="com.android.settings:id/content_frame",index="0").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.FrameLayout",resourceId="com.android.settings:id/main_content",index="0").child(className="android.widget.LinearLayout",resourceId="com.android.settings:id/container_material",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/list_container",index="0").child(className="android.widget.RelativeLayout",index="0").child(className="androidx.recyclerview.widget.RecyclerView",resourceId="com.android.settings:id/recycler_view",index="0").child(className="android.widget.LinearLayout",index="3").child(className="android.widget.RelativeLayout",resourceId="com.android.settings:id/text_layout",index="0").exists
            print(permissionstab)
            if permissionstab:
                print("clicking on permission tab")
                device(className="android.widget.FrameLayout",resourceId="com.android.settings:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.FrameLayout",resourceId="com.android.settings:id/content_parent",index="0").child(className="android.widget.FrameLayout",resourceId="com.android.settings:id/content_frame",index="0").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.FrameLayout",resourceId="com.android.settings:id/main_content",index="0").child(className="android.widget.LinearLayout",resourceId="com.android.settings:id/container_material",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/list_container",index="0").child(className="android.widget.RelativeLayout",index="0").child(className="androidx.recyclerview.widget.RecyclerView",resourceId="com.android.settings:id/recycler_view",index="0").child(className="android.widget.LinearLayout",index="3").child(className="android.widget.RelativeLayout",resourceId="com.android.settings:id/text_layout",index="0").click()
                for x in permissions:
                    time.sleep(2)
                    print(x)
                    permission=device(text=x).exists
                    if permission:
                        device(text=x).click()
                        allowonlywhileusingtheappbtn=device(className="android.view.ViewGroup",resourceId="android:id/decor_content_parent",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="1").child(className="android.view.ViewGroup",index="0").child(className="android.widget.FrameLayout",resourceId="com.android.permissioncontroller:id/nav_host_fragment",index="0").child(className="android.widget.LinearLayout",resourceId="com.android.permissioncontroller:id/app_permission_root",index="0").child(className="android.widget.ScrollView",resourceId="com.android.permissioncontroller:id/nested_scroll_view",index="0").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.LinearLayout",index="2").child(className="android.widget.RadioGroup",resourceId="com.android.permissioncontroller:id/radiogroup",index="1").child(className="android.widget.RadioButton",resourceId="com.android.permissioncontroller:id/allow_foreground_only_radio_button",index="0").exists
                        if allowonlywhileusingtheappbtn:
                            device(className="android.view.ViewGroup",resourceId="android:id/decor_content_parent",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="1").child(className="android.view.ViewGroup",index="0").child(className="android.widget.FrameLayout",resourceId="com.android.permissioncontroller:id/nav_host_fragment",index="0").child(className="android.widget.LinearLayout",resourceId="com.android.permissioncontroller:id/app_permission_root",index="0").child(className="android.widget.ScrollView",resourceId="com.android.permissioncontroller:id/nested_scroll_view",index="0").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.LinearLayout",index="2").child(className="android.widget.RadioGroup",resourceId="com.android.permissioncontroller:id/radiogroup",index="1").child(className="android.widget.RadioButton",resourceId="com.android.permissioncontroller:id/allow_foreground_only_radio_button",index="0").click()
                            device.press('back')
                            

def generalsettingsDeviceThemeAppearence(device):
    __openYoutube(device)
    __gotosettings(device)
    __settingsGeneral(device)
    device(text="Appearence").click() ##Not able to access using resourceId and className,  Error:Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!#Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!
    option=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="0").exists
    if option:
        device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="0").click()
        cancelButton=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").exists
        if cancelButton:
            device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").click()

def generalsettingsLightThemeAppearence(device):
    __openYoutube(device)
    __gotosettings(device)
    __settingsGeneral(device)
    device(text="Appearence").click() ##Not able to access using resourceId and className,  Error:Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!#Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!
    option=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="1").exists
    if option:
        device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="1").click()
        cancelButton=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").exists
        if cancelButton:
            device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").click()

def generalsettingsDarkThemeAppearence(device):
    __openYoutube(device)
    __gotosettings(device)
    __settingsGeneral(device)
    device(text="Appearence").click() ##Not able to access using resourceId and className,  Error:Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!#Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!
    option=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="2").exists
    if option:
        device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="2").click()
        cancelButton=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").exists
        if cancelButton:
            device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").click()


def generalsettingsAlwaysOnMutedPlaybackinFeeds(device):
    __openYoutube(device)
    __gotosettings(device)
    __settingsGeneral(device)
    device(text="Muted playback in feeds").click() ##Not able to access using resourceId and className,  Error:Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!#Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!
    option=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="0").exists
    if option:
        device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="0").click()
        cancelButton=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").exists
        if cancelButton:
            device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").click()

def generalsettingsWifiOnlyMutedPlaybackinFeeds(device):
    __openYoutube(device)
    __gotosettings(device)
    __settingsGeneral(device)
    device(text="Muted playback in feeds").click() ##Not able to access using resourceId and className,  Error:Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!#Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!
    option=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="1").exists
    if option:
        device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="1").click()
        cancelButton=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").exists
        if cancelButton:
            device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").click()
    
def generalsettingsOffMutedPlaybackinFeeds(device):
    __openYoutube(device)
    __gotosettings(device)
    __settingsGeneral(device)
    device(text="Muted playback in feeds").click() ##Not able to access using resourceId and className,  Error:Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!#Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!
    option=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="2").exists
    if option:
        device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="2").click()
        cancelButton=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").exists
        if cancelButton:
            device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").click()

def generalsettings5SecDoubletapToSeek(device):
    __openYoutube(device)
    __gotosettings(device)
    __settingsGeneral(device)
    device(text="Double-tap to seek").click() ##Not able to access using resourceId and className,  Error:Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!#Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!
    option=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="0").exists
    if option:
        device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="0").click()
        cancelButton=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").exists
        if cancelButton:
            device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").click()
        
def generalsettings10SecDoubletapToSeek(device):
    __openYoutube(device)
    __gotosettings(device)
    __settingsGeneral(device)
    device(text="Double-tap to seek").click() ##Not able to access using resourceId and className,  Error:Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!#Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!
    option=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="1").exists
    if option:
        device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="1").click()
        cancelButton=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").exists
        if cancelButton:
            device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").click()

def generalsettings15SecDoubletapToSeek(device):
    __openYoutube(device)
    __gotosettings(device)
    __settingsGeneral(device)
    device(text="Double-tap to seek").click() ##Not able to access using resourceId and className,  Error:Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!#Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!
    option=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="2").exists
    if option:
        device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="2").click()

def generalsettings20SecDoubletapToSeek(device):
    __openYoutube(device)
    __gotosettings(device)
    __settingsGeneral(device)
    device(text="Double-tap to seek").click() ##Not able to access using resourceId and className,  Error:Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!#Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!
    option=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="3").exists
    if option:
        device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="3").click()
        cancelButton=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").exists
        if cancelButton:
            device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").click()
        
def generalsettings30SecDoubletapToSeek(device):
    __openYoutube(device)
    __gotosettings(device)
    __settingsGeneral(device)
    device(text="Double-tap to seek").click() ##Not able to access using resourceId and className,  Error:Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!#Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!
    option=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="4").exists
    if option:
        device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="4").click()
        cancelButton=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").exists
        if cancelButton:
            device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").click()

def generalsettings60SecDoubletapToSeek(device):
    __openYoutube(device)
    __gotosettings(device)
    __settingsGeneral(device)
    device(text="Double-tap to seek").click() ##Not able to access using resourceId and className,  Error:Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!#Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!
    option=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="5").exists
    if option:
        device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/contentPanel",index="1").child(className="android.widget.ListView",resourceId="com.google.android.youtube:id/select_dialog_listview",index="0").child(className="android.widget.CheckedTextView",resourceId="android:id/text1",index="5").click()
        cancelButton=device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").exists
        if cancelButton:
            device(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",resourceId="com.google.android.youtube:id/parentPanel",index="0").child(className="android.widget.ScrollView",resourceId="com.google.android.youtube:id/buttonPanel",index="2").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.Button",resourceId="android:id/button2",index="0").click()

def __openYoutube(device):
    ##device.app_start('com.google.android.youtube')
    #device.app_stop_all()
    #device.press('recent')
    #device(className="android.widget.FrameLayout",resourceId="net.oneplus.launcher:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.FrameLayout",resourceId="net.oneplus.launcher:id/launcher",index="0").child(className="android.widget.FrameLayout",resourceId="net.oneplus.launcher:id/drag_layer",index="0").child(className="android.widget.RelativeLayout",resourceId="net.oneplus.launcher:id/overview_control_panel",index="3").child(className="android.widget.TextView",resourceId="net.oneplus.launcher:id/clear_all_button",index="1").click()
    device.press("home")
    device(className="android.widget.ImageView",resourceId="net.oneplus.launcher:id/page_indicator_caret").click()#for settings direct path
    device(scrollable=True).scroll.vert.forward()
    device(className="android.widget.TextView",resourceId="net.oneplus.launcher:id/icon",text="YouTube").click()
    time.sleep(3)
    #val=__isOffline(device)
    #print("Youtube is Offline: ",val)
    #if val is True:
    #    print("Youtube is Offline")
    #if val is False:
    #    print("Youtube is Online")
    #__checkAccessibilityplayerpopup(device)
    

def __isOffline(device):
    status=device(className="android.widget.LinearLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/slim_status_bar_player_container",index="0").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/navigation_bar_divider_frame",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/accessibility_layer_container",index="1").child(className="android.widget.LinearLayout",resourceId="com.google.android.youtube:id/bottom_bar_container",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/slim_status_bar",index="1").child(className="android.widget.TextView",resourceId="com.google.android.youtube:id/text",text="No connection",index="0").exists
    if status:
        return True
    else :
        return False  

def __checkAccessibilityplayerpopup(device):
    print("Checking Accessibility Player Popup")
    status=device(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/slim_status_bar_player_container",index="0").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/navigation_bar_divider_frame",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/accessibility_layer_container",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/bottom_ui_container",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/mealbar",index="0").child(className="android.widget.GridLayout",index="0").child(className="android.view.ViewGroup",index="2").child(className="android.widget.Button",resourceId="com.google.android.youtube:id/mealbar_dismiss_button",index="0").exists
    if status:
        device(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/slim_status_bar_player_container",index="0").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/navigation_bar_divider_frame",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/accessibility_layer_container",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/bottom_ui_container",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/mealbar",index="0").child(className="android.widget.GridLayout",index="0").child(className="android.view.ViewGroup",index="2").child(className="android.widget.Button",resourceId="com.google.android.youtube:id/mealbar_dismiss_button",index="0").click()
        print("Accessibility Player Popup Dismissed")
        
def __gotosettings(device):
    val=__isOffline(device)
    if val is False:
        print("Youtube is Online")
        __clickOnMenu(device)
        __clickonSettings(device)
        print("reached settings")
        
def __settingsGeneral(device):
    print("working on general settins")
    generalsettingsOption=device(className="android.widget.LinearLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/settings_fragments",index="1").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/list_container",index="0").child(className="android.support.v7.widget.RecyclerView",resourceId="com.google.android.youtube:id/recycler_view",index="0").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.RelativeLayout",index="0").exists
    print(generalsettingsOption)
    if generalsettingsOption:
        device(className="android.widget.LinearLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/settings_fragments",index="1").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/list_container",index="0").child(className="android.support.v7.widget.RecyclerView",resourceId="com.google.android.youtube:id/recycler_view",index="0").child(className="android.widget.LinearLayout",index="0").child(className="android.widget.RelativeLayout",index="0").click()


def __clickOnMenu(device):
    menuButton=device(className="android.widget.LinearLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/slim_status_bar_player_container",index="0").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/navigation_bar_divider_frame",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/accessibility_layer_container",index="1").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/next_gen_watch_container_layout",index="0").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/watch_while_layout_coordinator_layout",index="0").child(className="android.widget.LinearLayout",resourceId="com.google.android.youtube:id/appbar_layout",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/toolbar_container",index="0").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/toolbar",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",index="1").child(className="android.widget.ImageView",index="2").exists
    if menuButton:
        device(className="android.widget.LinearLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/slim_status_bar_player_container",index="0").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/navigation_bar_divider_frame",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/accessibility_layer_container",index="1").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/next_gen_watch_container_layout",index="0").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/watch_while_layout_coordinator_layout",index="0").child(className="android.widget.LinearLayout",resourceId="com.google.android.youtube:id/appbar_layout",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/toolbar_container",index="0").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/toolbar",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",index="1").child(className="android.widget.ImageView",index="2").click()
    menuButton=device(className="android.widget.LinearLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/slim_status_bar_player_container",index="0").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/navigation_bar_divider_frame",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/accessibility_layer_container",index="1").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/next_gen_watch_container_layout",index="0").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/watch_while_layout_coordinator_layout",index="0").child(className="android.widget.LinearLayout",resourceId="com.google.android.youtube:id/appbar_layout",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/toolbar_container",index="0").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/toolbar",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/mobile_topbar_avatar",index="3").child(className="android.widget.ImageView",resourceId="com.google.android.youtube:id/image",index="0").exists
    if menuButton:
        device(className="android.widget.LinearLayout",resourceId="com.google.android.youtube:id/action_bar_root",index="0").child(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/slim_status_bar_player_container",index="0").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/navigation_bar_divider_frame",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/accessibility_layer_container",index="1").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/next_gen_watch_container_layout",index="0").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/watch_while_layout_coordinator_layout",index="0").child(className="android.widget.LinearLayout",resourceId="com.google.android.youtube:id/appbar_layout",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/toolbar_container",index="0").child(className="android.view.ViewGroup",resourceId="com.google.android.youtube:id/toolbar",index="0").child(className="android.support.v7.widget.LinearLayoutCompat",index="1").child(className="android.widget.FrameLayout",resourceId="com.google.android.youtube:id/mobile_topbar_avatar",index="3").child(className="android.widget.ImageView",resourceId="com.google.android.youtube:id/image",index="0").click()

def __clickonSettings(device):
    print("Working on It")
    settingsButton=device(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.LinearLayout",index="0").child(className="android.support.v7.widget.RecyclerView",resourceId="com.google.android.youtube:id/list",index="1").child(className="android.widget.LinearLayout",index="2").child(className="android.widget.RelativeLayout",index="1").child(className="android.widget.TextView",resourceId="com.google.android.youtube:id/title",text="Settings",index="0").exists
    if settingsButton:
        device(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.LinearLayout",index="0").child(className="android.support.v7.widget.RecyclerView",resourceId="com.google.android.youtube:id/list",index="1").child(className="android.widget.LinearLayout",index="2").child(className="android.widget.RelativeLayout",index="1").child(className="android.widget.TextView",resourceId="com.google.android.youtube:id/title",text="Settings",index="0").click()
    settingsButton=device(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.LinearLayout",index="0").child(className="android.support.v7.widget.RecyclerView",resourceId="com.google.android.youtube:id/list",index="1").child(className="android.widget.LinearLayout",index="10").child(className="android.widget.RelativeLayout",index="1").child(className="android.widget.TextView",resourceId="com.google.android.youtube:id/title",index="0").exists
    if settingsButton:
        device(className="android.widget.FrameLayout",resourceId="android:id/content",index="0").child(className="android.widget.LinearLayout",index="0").child(className="android.support.v7.widget.RecyclerView",resourceId="com.google.android.youtube:id/list",index="1").child(className="android.widget.LinearLayout",index="10").child(className="android.widget.RelativeLayout",index="1").child(className="android.widget.TextView",resourceId="com.google.android.youtube:id/title",index="0").click()


def __closeYoutube(device):
    print("kranthi")
    ##device.app_clear('com.google.android.youtube')